name: Build & Test iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies via CocoaPods
        run: pod install
        working-directory: ./ # ajuste se necessário

      - name: List schemes in workspace
        run: xcodebuild -workspace BankApp.xcworkspace -list

      - name: Build project
        run: |
          xcodebuild \
            -workspace BankApp.xcworkspace \
            -scheme TransferModule \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            clean build

      - name: Run tests
        run: |
          xcodebuild \
            -workspace BankApp.xcworkspace \
            -scheme TransferModule \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            test
